version: "3.6"
services:
  django-test:
    build:
      dockerfile: images/django-test.dockerfile
      context: .
    command: python manage.py test -v 3
    volumes:
    - ./data:/opt/mapaly/data
    environment:
    - SELENIUM_CHROME=/usr/bin/google-chrome
  intermap-test:
    build:
      dockerfile: ../images/intermap-test.dockerfile
      context: intermap
    command: npm run test