version: "3.6"
services:
  django:
    build:
      dockerfile: images/django.dockerfile
      context: .
    restart: always
    volumes:
    - ./data:/opt/mapaly/data
    - static:/opt/mapaly/static
  nginx:
    image: nginx:1.19.0
    restart: always
    ports:
    - 1133:1133
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - static:/opt/mapaly/static:ro
    depends_on:
    - django

volumes:
  static:
