version: "3.6"
services:
  django:
    build: .
    restart: always
    command: bash start.sh
    volumes:
    - ./data:/opt/mapaly/data
    - static:/opt/mapaly/static
  nginx:
    image: nginx:1.17.2
    restart: always
    ports:
    - 1133:1133
    volumes:
    - static:/opt/mapaly/static:ro
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - django

volumes:
  static: