# Generated by Django 3.1.1 on 2020-09-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_front_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
