# Generated by Django 3.1.1 on 2020-09-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_quiz_top"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="front_image",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=150, unique=True),
        ),
    ]
