# Generated by Django 3.1.2 on 2020-10-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_quiz_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="language",
            field=models.CharField(
                choices=[("es", "Español"), ("en", "English")], max_length=2
            ),
        ),
    ]
