# Generated by Django 3.1.2 on 2020-10-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("score", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="time",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
