name: Push test

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build images
      run: docker-compose -f docker-compose.test.yml -f docker-compose.yml build
    - name: Test Python
      run: docker-compose -f docker-compose.test.yml -f docker-compose.yml run django-test
    - name: Test JavaScript
      run: docker-compose -f docker-compose.test.yml -f docker-compose.yml run intermap-test
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==1.2.2
        poetry install --no-root
    - name: Execute mypy
      run: poetry run mypy .
    - name: Execute black
      run: poetry run black . --check
