name: Push test

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build images
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml build
    - name: Run flake8
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run lint-python

    